export const playerMarkup = String.raw`<div class="app full-deck" id="app">
  <header class="titlebar">
    <a class="brand" href="/" aria-label="Atiga Amp beranda"><span class="brand-emblem">A</span><span>ATIGA</span><b>AMP</b><span class="version">CT–03</span></a>
    <div class="title-motto">STEREO CASSETTE MUSIC SYSTEM</div>
    <div class="title-actions"><span class="local-indicator"><i></i> LOCAL SOURCE</span><button class="icon-button" id="compact" title="Mode ringkas" aria-label="Mode ringkas" data-icon="minimize"></button><button class="icon-button" id="help" title="Panduan dan pintasan" aria-label="Panduan dan pintasan" data-icon="help"></button></div>
  </header>
  <aside class="sidebar">
    <div class="side-brand"><span>ATIGA</span><strong>TAPE INDEX</strong><small>STEREO MUSIC LIBRARY</small></div>
    <div class="sidebar-heading">SOURCE SELECTOR</div>
    <nav aria-label="Koleksi musik"><button class="nav-item active" data-view="all"><span data-icon="library"></span>Semua musik<span class="nav-count" id="all-count">6</span></button><button class="nav-item" data-view="favorites"><span data-icon="heart"></span>Favorit<span class="nav-count" id="favorite-count">0</span></button><button class="nav-item" data-view="recent"><span data-icon="history"></span>Terakhir diputar</button></nav>
    <div class="sidebar-heading playlist-heading">DAFTAR PUTAR <button class="icon-button small" id="new-playlist" title="Buat daftar putar" aria-label="Buat daftar putar" data-icon="plus"></button></div><nav id="playlist-nav" aria-label="Daftar putar"></nav>
    <div class="sidebar-footer"><div class="collection-icon" data-icon="folder"></div><strong>LOCAL TAPE ARCHIVE</strong><p>Musik Anda tetap tersimpan<br>di perangkat ini.</p><button class="folder-button" id="import-folder"><span data-icon="folder-plus"></span> PILIH FOLDER</button><span class="privacy-note"><span data-icon="shield"></span> PRIVATE / OFFLINE</span></div>
  </aside>
  <main class="library">
    <div class="page-heading"><div><div class="eyebrow"><span></span> CASSETTE BAY / SIDE A</div><h1 id="view-title">Semua musik<span>.</span></h1><p id="collection-summary">Koleksi pribadi, dengan sentuhan klasik.</p></div><button class="primary-button" id="import"><span data-icon="plus"></span> LOAD TAPE</button></div>
    <section class="featured" aria-label="Kaset yang sedang diputar">
      <div class="deck-rail"><span></span><p>AUTOMATIC LOCAL TAPE SELECTOR</p><span></span></div>
      <div class="cassette-window"><div class="cassette-topline"><span>A</span><strong>ATIGA RECORDING TAPE</strong><small>TYPE I · NORMAL POSITION</small></div><div class="tape-reels" aria-hidden="true"><span class="reel reel-left"><i></i></span><span class="tape-path"></span><span class="reel reel-right"><i></i></span></div><div class="tape-label"><span>ATIGA / PLAYER'S SERIES</span><strong>C-60</strong></div><div class="tape-screws" aria-hidden="true"><i></i><i></i><i></i><i></i></div></div>
      <div class="cassette-door"><div class="door-window"><span class="counter">000</span><span class="head"></span><span class="counter">001</span></div><small>SINGLE / CASSETTE / SUPER QUIET MECHANISM</small></div>
      <div class="mechanism-buttons"><button data-deck-control="previous">REW</button><button data-deck-control="next">FF</button><button data-deck-control="stop">STOP</button><button data-deck-control="play">PLAY</button><button class="rec" data-deck-control="play">REC</button></div>
      <div class="power-module" aria-hidden="true"><span>POWER</span><i></i><small>ON&nbsp;&nbsp;&nbsp;OFF</small></div>
      <div class="featured-copy"><span class="feature-label">MANUAL TAPE LOADER</span><button id="play-session" class="session-button"><span data-icon="upload"></span> Tambah musik <span class="session-arrow">↗</span></button></div>
    </section>
    <div class="library-toolbar"><div class="track-tabs"><button class="track-tab active" id="track-tab">TAPE INDEX <span id="track-count">6</span></button><button class="track-tab" id="queue-tab">PLAY QUEUE <span id="queue-count">0</span></button></div><div class="table-actions"><label class="search"><span data-icon="search"></span><input id="search" placeholder="Cari lagu atau artis…" aria-label="Cari lagu atau artis" autocomplete="off" /><kbd>/</kbd></label><button class="icon-button" id="sort" aria-label="Urutkan lagu berdasarkan judul" title="Urutkan berdasarkan judul" data-icon="sort"></button></div></div>
    <div class="track-table-wrap"><table class="track-table"><thead><tr><th class="number-col">#</th><th>PROGRAM / TITLE</th><th class="album-col">ALBUM</th><th class="format-col">TAPE</th><th class="duration-col"><span data-icon="clock" aria-label="Durasi"></span></th><th class="actions-col"></th></tr></thead><tbody id="tracks"></tbody></table><div class="empty-state" id="empty" hidden><span data-icon="music"></span><h3>Tape bay kosong.</h3><p>Tambahkan musik untuk mulai mendengarkan.</p></div></div>
    <div class="library-bottom"><span id="library-total">6 lagu demo</span><span><i></i> DECK READY</span></div><div class="drop-hint"><span data-icon="upload"></span> Tarik file musik ke deck <span>MP3 · WAV · OGG · FLAC*</span></div>
  </main>
  <aside class="now-panel">
    <div class="panel-heading">TWIN LEVEL METER <span class="tiny-bars"><i></i><i></i><i></i></span></div>
    <div class="vu-rack" aria-label="Meter level stereo"><div class="vu-meter"><span class="vu-scale">−20&nbsp;&nbsp;−10&nbsp;&nbsp;−5&nbsp;&nbsp;0&nbsp;&nbsp;+3</span><div class="vu-arc"></div><i class="vu-needle"></i><strong>LEFT</strong></div><div class="vu-meter"><span class="vu-scale">−20&nbsp;&nbsp;−10&nbsp;&nbsp;−5&nbsp;&nbsp;0&nbsp;&nbsp;+3</span><div class="vu-arc"></div><i class="vu-needle vu-needle-right"></i><strong>RIGHT</strong></div></div>
    <div class="signal-lamps"><span><i class="lamp red"></i>PEAK</span><span><i class="lamp"></i>REC</span><span><i class="lamp green"></i>ON TAPE</span></div>
    <div class="knob-bank" aria-label="Kontrol audio"><div class="knob-control"><i class="knob"></i><span>ENHANCER</span></div><div class="knob-control"><i class="knob"></i><span>BALANCE</span></div><div class="knob-control"><i class="knob knob-red"></i><span>VOLUME</span></div></div>
    <div class="switch-bank" aria-hidden="true"><span><i></i>PAUSE</span><span><i></i>LOOP</span><span><i></i>RAND</span><span><i></i>MONITOR</span></div>
    <div class="right-control-rail" aria-hidden="true"><span><i></i>EQ</span><span><i></i>FLANGER</span><span><i></i>CHORUS</span><span><i></i>PHONES</span></div>
    <div class="album-art large-art" id="now-art" data-art="0"><div class="art-grid"></div><span class="art-label">NOW PLAYING<br><small>ATIGA HIGH FIDELITY</small></span><div class="art-sun"></div><div class="art-horizon"></div><span class="art-title">AFTER HOURS<span>ATIGA SESSIONS</span></span><span class="art-corner">A</span></div>
    <div class="now-track"><div><small>PROGRAM</small><h2 id="now-title">Amber Skies</h2><p id="now-artist">Atiga Sessions</p></div><button class="icon-button" id="now-favorite" aria-label="Tambahkan ke favorit" data-icon="heart"></button></div><div class="audio-tags"><span id="now-format">WAV</span><span id="now-quality">DEMO AUDIO</span><span>STEREO</span></div>
    <section class="spectrum-box"><div class="instrument-heading"><span>SPECTRUM ANALYZER</span><span class="live-label" id="spectrum-status">STANDBY</span></div><canvas id="spectrum" aria-label="Spektrum frekuensi audio"></canvas><div class="frequency-labels"><span>60</span><span>250</span><span>1K</span><span>4K</span><span>16K</span></div></section>
    <button class="eq-toggle" id="eq-toggle" aria-expanded="false"><span data-icon="sliders"></span><span>DSP MANAGER <small id="preset-label">Datar</small></span><span class="eq-status">10 BAND</span><span data-icon="chevron"></span></button>
    <div class="next-up"><div class="panel-heading">NEXT PROGRAM <button class="text-button" id="show-queue">QUEUE <span>↗</span></button></div><div class="next-track" id="next-track"></div></div><div class="panel-signature"><span class="brand-emblem mini">A</span><span>ATIGA AUDIO LAB / EST. 2026</span></div>
  </aside>
  <footer class="player">
    <div class="player-track"><div class="mini-art" id="player-art" data-art="0"><span>AA</span></div><div><small>NOW PLAYING</small><strong id="player-title">Amber Skies</strong><span id="player-artist">Atiga Sessions <i>·</i> Demo</span></div><button class="icon-button" id="player-favorite" aria-label="Tambahkan ke favorit" data-icon="heart"></button></div>
    <div class="transport"><div class="transport-labels"><span>SHUFFLE</span><span>REW</span><span>PLAY / PAUSE</span><span>FF</span><span>REPEAT</span></div><div class="transport-buttons"><button class="icon-button mech-button" id="shuffle" aria-label="Acak" aria-pressed="false" title="Acak" data-icon="shuffle"></button><button class="icon-button mech-button skip-button" id="previous" aria-label="Lagu sebelumnya" data-icon="previous"></button><button class="play-button mech-button" id="play" aria-label="Putar" data-icon="play"></button><button class="icon-button mech-button skip-button" id="next" aria-label="Lagu berikutnya" data-icon="next"></button><button class="icon-button mech-button" id="repeat" aria-label="Ulangi: mati" title="Ulangi: mati" data-icon="repeat"></button></div><div class="seek-row"><time id="elapsed">00:00</time><input type="range" id="seek" min="0" max="100" step="0.1" value="0" aria-label="Posisi pemutaran" /><time id="duration">00:32</time></div></div>
    <div class="player-tools"><div class="tool-block"><span>MONITOR</span><button class="icon-button" id="mute" aria-label="Bisukan" data-icon="volume"></button></div><label class="volume-control"><span>OUTPUT LEVEL</span><input type="range" id="volume" min="0" max="1" step="0.01" value="0.7" aria-label="Volume" /></label><span class="tool-divider"></span><button class="icon-button tool-square" id="player-eq" title="Ekualiser" aria-label="Buka ekualiser" data-icon="sliders"></button><button class="icon-button tool-square" id="player-queue" title="Antrean" aria-label="Tampilkan antrean" data-icon="queue"></button></div>
  </footer>
  <div class="statusbar"><span><i></i> POWER ON <span class="status-separator">/</span> ATIGA LOGIC CONTROL</span><span>STEREO CASSETTE MUSIC DECK <span class="status-separator">·</span> CT–03</span></div>
</div>
<input type="file" id="file-input" accept="audio/*,.flac,.ogg,.m4a,.opus,.aiff,.webm" multiple hidden /><input type="file" id="folder-input" webkitdirectory multiple hidden /><div class="drop-overlay" id="drop-overlay" hidden><span data-icon="music"></span><h2>Load your tape.</h2><p>Lepaskan file audio untuk menambah koleksi.</p></div>
<dialog id="eq-dialog"><form method="dialog" class="dialog-heading"><div><div class="eyebrow">ATIGA / TONE CONTROL</div><h2>Ekualiser<span>.</span></h2></div><button class="icon-button" aria-label="Tutup ekualiser" data-icon="close"></button></form><div class="eq-controls"><label>Prasetel <select id="eq-preset"><option value="Flat">Datar</option><option value="Warm">Hangat</option><option value="Bass Boost">Penguat bas</option><option value="Vocal">Vokal</option><option value="Bright">Cerah</option><option value="Custom">Kustom</option></select></label><button class="text-button" id="eq-reset">Atur ulang</button></div><div class="eq-bands" id="eq-bands"></div><p class="dialog-note">Sesuaikan karakter suara. Perubahan langsung diterapkan saat musik diputar.</p></dialog>
<dialog id="playlist-dialog"><form id="playlist-form"><div class="dialog-heading"><h2>Daftar putar baru<span>.</span></h2><button type="button" class="icon-button" id="close-playlist" aria-label="Tutup" data-icon="close"></button></div><label class="field-label" for="playlist-name">Nama daftar putar</label><input id="playlist-name" class="text-input" placeholder="Misalnya: Teman bekerja" maxlength="48" required /><button class="primary-button form-submit" type="submit">Buat daftar putar <span data-icon="plus"></span></button></form></dialog>
<dialog id="track-dialog"><form method="dialog" class="dialog-heading"><h2 id="track-dialog-title">Opsi lagu</h2><button class="icon-button" aria-label="Tutup" data-icon="close"></button></form><div id="track-options"></div></dialog>
<dialog id="help-dialog"><form method="dialog" class="dialog-heading"><h2>ATIGA AMP CT–03<span>.</span></h2><button class="icon-button" aria-label="Tutup panduan" data-icon="close"></button></form><p>Pemutar musik lokal dengan wajah cassette deck klasik. Tambahkan file atau folder musik, lalu gunakan tombol mekanis di panel utama.</p><div class="shortcut-list"><span>Putar / jeda <kbd>Spasi</kbd></span><span>Cari koleksi <kbd>/</kbd></span><span>Lagu berikutnya <kbd>Alt →</kbd></span><span>Lagu sebelumnya <kbd>Alt ←</kbd></span></div><p>File yang diimpor disimpan di perangkat ini, tanpa diunggah.</p></dialog><div role="status" id="toast" class="toast" hidden></div><audio id="audio" preload="auto"></audio>`;
